#!/usr/bin/python
import os
#import glob
#import os.path as goo

os.chdir('../../PRODUCTION/shots')
print "is shot ready?"
shots=['a01', 'a02', 'a03', 'a04', 'a05', 'a06', 'a07', 'b03', 'c01', 'c04', 'c05', 'c06', 'd01', 'd02', 'd03', 'd04', 'd05', 'd06', 'd07', 'd08', 'd09', 'd10', 'd11', 'd12', 'd13', 'd14', 'd15', 'd16', 'd19', 'e02', 'e03', 'e04', 'e05', 'e06', 'e07', 'f01', 'f02', 'f03', 'f04', 'f05', 'f07', 'f08', 'f09', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'g02', 'g03', 'g04', 'g05', 'g06', 'g07', 'g08', 'g09', 'g10', 'g11', 'g12', 'h01', 'h03', 'h04', 'h05', 'h06', 'h07', 'h09', 'i01', 'i02', 'i04']
count=0
for dunno in shots:
    file="No"
    check=os.listdir('./'+shots[count] +'/renders/latest/')
    if len(check)>0:
        file= "Yes"
        frames=str(len(check))
        print shots[count] +': ' +file +' --- ' +frames +' frames rendered'
    else:
        print shots[count] +': ' +file
    count=count+1

raw_input("Press enter to exit")

